FlipsideCrypto/flow-models

- models/core/core__fact_transactions.sql
- models/core/core__fact_transactions.yml
- models/gold/gold__transactions.sql
- models/gold/gold__transactions.yml
Known failed tests are all `not_null`s related to [PL-54](https://team-1612274056224.atlassian.net/browse/PL-54). Issue resolved as of 5/16 and forward. Fill in progress for the gap from block 29,420,498 to 29,883,212.
> An 1221/gold transactions

- macros/sp_create_prod_clone.sql
- adding a cloning step to clone stages in dev refresh sp
> clone stages to dev

- dbt_project.yml
- macros/create_udfs.sql
- macros/sp_create_bulk_get_topshot_moments_minted_metadata.sql
- macros/sp_create_prod_clone.sql
- macros/udf_bulk_get_topshot_moments_minted_metadata.sql
- models/silver/silver__all_topshot_moments_minted_metadata_needed.sql
- models/sources.yml
- packages.yml
- create view/sp/udf to integrate topshot metadata call
> An 1625/integrate moments minted api

- data/seeds__celer_chain_ids.csv
- models/core/core__ez_bridge_transactions.sql
- models/core/core__ez_dex_swaps.yml
- models/core/core__ez_nft_sales.sql
- models/core/core__ez_nft_sales.yml
- models/core/core__ez_token_transfers.sql
- models/core/core__fact_bridge_transactions.yml
- models/core/core__fact_nft_sales.yml
- models/core/core__fact_swaps.yml
- models/silver/silver__blocks.yml
- models/silver/silver__bridge_blocto.sql
- models/silver/silver__bridge_celer.sql
- models/silver/silver__event_attributes.yml
- models/silver/silver__nft_sales.yml
- models/silver/silver__nft_topshot_sales.yml
- models/silver/silver__nft_transactions_fabricant.yml
- models/silver/silver__nft_transactions_secondary_market.sql
- models/silver/silver__nft_transactions_secondary_market.yml
- models/silver/silver__token_transfers.sql
Appropriate refresh:
`dbt seed --full-refresh`
`dbt run -s tag:bridge silver__nft_transactions_secondary_market+ --full-refresh`
`dbt run -s models/core`
(~15-20mins on a medium)
Should clear up test failures (except for gaps) in `dbt test -s models/core`
> AN-1945/fixes

- models/bronze/bronze__moments_metadata.sql
- models/sources.yml
- models/streamline/streamline__all_topshot_moments_minted_metadata_needed.sql
- models/streamline/streamline__allday_moments_metadata_needed.sql
- use new location for external table sources
> source external tables from streamline db

- models/streamline/streamline__all_topshot_moments_minted_metadata_needed.sql
- models/streamline/streamline__allday_moments_metadata_needed.sql
- can now use silver to run the view because we only need to run this once per day
> use silver table instead of bronze

- models/core/core__ez_token_transfers.sql
- models/core/core__fact_blocks.yml
- models/core/core__fact_transactions.yml
- Adds threshold for gaps
- Excludes swappair from transfers
> Minor test fixes

- data/seeds__blocto_teleport_labels.csv
- data/seeds__celer_chain_ids.csv
- data/seeds__network_version.csv
- models/core/core__ez_token_transfers.yml
- models/silver/labels/silver__labels_pools.yml
- python_scripts/test_alert/dbt_test_alert.py
- tests/tests__block_timestamp_order.sql
- adds data to seed files
- adjusts tests as needed
blocks will need a re-run to fill-in network version
bridge models will need a re-run to fill in new blockchain id labels
> test tweaks

- .github/workflows/dbt_run_daily_dev_refresh.yml
- .github/workflows/dbt_run_hourly.yml
- .github/workflows/dbt_run_moments_metadata.yml
update dbt commands to no longer use matrix gha input
> update workflow template

- models/core/core__dim_moment_metadata.sql
- models/core/core__dim_moment_metadata.yml
Excludes 2 edition IDs from the core view
> upd metadata view

- data/seeds__celer_chain_ids.csv
- models/silver/nft/silver__nft_topshot_pack_sales.yml
> AN-3508-flow-add-248-id

- Makefile
- macros/streamline/api_integrations.sql
- macros/streamline/get_base_table_udft.sql
- macros/streamline/streamline_udfs.sql
- models/streamline/README.md
- Adds makefile ` chainhead udf/api integration` directives 
- Adds `api integration  / udf macros`
- Adds grant select to role macro
- Adds run sql query and log results macro **TODO**: move this macro to `fsc-utils`
> streamline flow chainhead udf

- Makefile
- analysis/test.sql
- macros/create_udfs.sql
- macros/streamline/api_integrations.sql
- macros/streamline/streamline_udfs.sql
- macros/utils.sql
- models/silver/streamline/README.md
- models/silver/streamline/core/complete/streamline__complete_get_blocks.sql
- models/silver/streamline/core/history/streamline__get_blocks_history.sql
- models/silver/streamline/core/streamline__blocks.sql
- Adds `get_chainhead, bulk_grpc, get_base_table` udf creation `dbt macros` & `makefile` directives
- Adds `if_data_call_function` utils macro
- Adds `complete get_blocks` & `history get_blocks` dbt models and `udf_bulk_grpc` calls
- Adds `streamline_blocks` dbt model
> Stream 97 streamline blocks

- macros/utils.sql
- models/silver/streamline/core/history/streamline__get_blocks_history.sql
- Fixes `json request` attribute for `get_block_history` model
- Adds `grants` macro for future `views/tables/functions` in a schema to role
> fix json parse for bulk grpc udf request | add grants macro

- macros/streamline/api_integrations.sql
- macros/streamline/streamline_udfs.sql
- Updates dev udf urls due to re-deployment needed to add event-notifications
> update dev udf urls

- .github/workflows/dbt_run_streamline_blocks.yml
- models/silver/streamline/core/history/streamline__get_blocks_history.sql
- models/silver/streamline/core/history/streamline__get_collections_history.sql
- models/silver/streamline/core/history/streamline__get_transaction_results_history.sql
- models/silver/streamline/core/history/streamline__get_transactions_history.sql
22 has been running for ~3 hrs, seem to be settling in around only 20k per hour (~2500/hr to keep up with chainhead).
Adding in 3 more versions to get those syncing in parallel
> Add 3 Mainnets 19-21 to Blocks

- .github/workflows/dbt_run_streamline_transaction_results.yml
Defines `producer_batch_size` = 60,000 and `worker_batch_size` = 2,000. Increases lambda concurrency to 30
> Increase RT tx results batching

- Makefile
- dbt_project.yml
- macros/streamline/api_integrations.sql
- macros/streamline/streamline_udfs.sql
- models/silver/streamline/core/history/blocks/streamline__get_blocks_history_mainnet22.sql
- Adds `us-east-2` `bulk_grpc` udfs
- Adds `udf 2` make directives
- Adds POC `mainnet22` `udf_bulk_grpc_us_east_2` history backfill model
> adds multi region udfs

- .github/workflows/dbt_run_streamline_blocks.yml
20 and 21 are filled, deleting from workflow
> upd blocks backfill schedule, del 20 and 21

- .github/workflows/dbt_run_scheduled.yml
- .github/workflows/dbt_run_streamline_hourly.yml
- models/silver/core/silver__streamline_events.sql
- models/silver/core/silver__streamline_transactions_final.sql
Missed a model on the workflow
> Upd tags on workflow to include silver__streamline_events

- models/silver_cw/transfers/silver__token_transfers.sql
CW xfers model will require FR
> upd expiring model to incl usdc

- .github/workflows/dbt_run_scheduled.yml
- .github/workflows/dbt_test.yml
- models/gold/core/core__fact_blocks.yml
Scheduled Workflow:
- Changes `scheduled` to `streamline_scheduled` to disable the CW workflow
- Passes in `STREAMLINE_START_BLOCK` via a repository variable so the range can be configured from the repo, rather than changing the `dbt_project.yml` which would require a PR.
Test Workflow:
- Adds CLI vars which are input for the gap tests on the 4 streamline models
> Upd workflows for streamline models. Disables CW models.

- models/silver/_observability/silver_observability__blocks_completeness.sql
- models/silver/_observability/silver_observability__txs_completeness.sql
Update observability models to use the Streamline data
> An 4030/obs model migration

- .github/workflows/dbt_run_scheduled.yml
- .github/workflows/dbt_run_streamline_blocks.yml
- .github/workflows/dbt_run_streamline_collections.yml
- .github/workflows/dbt_run_streamline_transaction_results.yml
- .github/workflows/dbt_run_streamline_transactions.yml
Changes schedule back to 3x/hr. Will merge after ~a day of 4x/hr
> chg schedule to 3x/hour

- models/silver/transfers/silver__token_transfers_s.sql
> fix: usdc mint transfers

- models/silver/core/silver__streamline_events.sql
It will require a full refresh
> fix: parse

- .github/workflows/dbt_docs_update.yml
- .github/workflows/dbt_run_daily_dev_refresh.yml
- .github/workflows/dbt_run_deployment.yml
- .github/workflows/dbt_run_history.yml
- .github/workflows/dbt_run_moments_metadata.yml
- .github/workflows/dbt_run_scheduled.yml
- .github/workflows/dbt_run_scheduled_non_core.yml
- .github/workflows/dbt_test.yml
- dbt_project.yml
- package-lock.yml
- profiles.yml
- requirements.txt
> An 4442 flow dbt1.7

- Makefile
- macros/streamline/streamline_udfs.sql
- Updates dev udf 2 with proper url
- Updates `make tx_results_history` directive with proper dbt node
> fix udf 2 api integration

- .github/workflows/dbt_docs_update.yml
- .github/workflows/dbt_run_adhoc.yml
- .github/workflows/dbt_run_daily_dev_refresh.yml
- .github/workflows/dbt_run_deployment.yml
- .github/workflows/dbt_run_history.yml
- .github/workflows/dbt_run_moments_metadata.yml
- .github/workflows/dbt_run_scheduled.yml
- .github/workflows/dbt_run_scheduled_non_core.yml
- .github/workflows/dbt_test.yml
note - pushed upd to requirements.txt previously
> upd workflows to use requirements.txt

- models/silver/stats/silver_stats__core_metrics_hourly.sql
> stats authorizer replacement

- .github/workflows/dbt_run_adhoc_with_alert.yml
- python/dbt_slack_notification.py
To run GHA from a branch (for dev testing):
Add on push, which will cause the workflow to run on any push to this branch
```
on:
push:
branches:
- "adhoc-with-alert"
```
All input vars must be given a default value, as inputs are not accepted with on push
```
"${{ inputs.warehouse || 'DBT' }}"
"${{ inputs.environment || 'dev' }}"
"${{ inputs.dbt_command || 'dbt debug' }}"
```
These steps are not necessary in prod, as workflow_dispatch is the only way it will be run
> new workflow/adhoc with alert

- macros/streamline/api_integrations.sql
- macros/streamline/streamline_udfs.sql
- Adds `flow-evm` `bulk_rest_api_v2` udfs
- Adds `flow-evm` `api_integrations`
> add flow evm v2 udfs

- .github/workflows/dbt.yml
- .github/workflows/dbt_integration_test.yml
- Adds reusable GHA to run dbt workflows with `worflow_call` triggers
- Adds GHA to run integration tests from the `livequery` dbt package
> Livequery integration test gha

- models/descriptions/actors.md
- models/descriptions/address.md
- models/descriptions/argument_name.md
- models/descriptions/event_type.md
- models/gold/core/core__ez_transaction_actors.sql
- models/gold/core/core__ez_transaction_actors.yml
- models/silver/curated/silver__transaction_actors.sql
- models/silver/curated/silver__transaction_actors.yml
See thread in Slack for parameters.
> AN-5100/tx actors model

- models/evm/silver/core/silver_evm__receipts.sql
On friday evening, the flowEVM receipts response changed from returning certain data as an int to hex-encoded. Upd checks for `0x` and decodes, if necessary
```sql
select * from streamline.flow.evm_receipts
where array_size(data:result::array) > 1
and partition_key >= 997000
and block_number in (997488, 1001904)
;
```
> AN-5238/fix evm receipts model

- .github/workflows/dbt_run_scheduled_transaction_entries_realtime.yml
- models/sources.yml
- models/streamline/external/storefront_items/bronze_api__FR_minting_assets.sql
- models/streamline/external/storefront_items/bronze_api__minting_assets.sql
- models/streamline/external/storefront_items/silver_api__minting_assets.sql
- models/streamline/external/storefront_items/silver_api__storefront_items.sql
- models/streamline/external/storefront_items/silver_api__storefront_items.yml
- models/streamline/external/storefront_items/streamline__minting_assets_realtime.sql
External Table Config: https://github.com/FlipsideCrypto/streamline-snowflake/pull/189
> AN-5517/api integration - GET minting/assets

- models/evm/bronze/bronze__decoded_logs.sql
- models/evm/bronze/bronze__decoded_logs_fr.sql
- models/evm/descriptions/contract_abis.md
- models/evm/descriptions/contracts.md
- models/evm/descriptions/decoded_event_logs.md
- models/evm/descriptions/transfers.md
- models/evm/gold/core/core_evm__dim_contracts.sql
- models/evm/gold/core/core_evm__dim_contracts.yml
- models/evm/gold/decoder/core_evm__dim_contract_abis.sql
- models/evm/gold/decoder/core_evm__dim_contract_abis.yml
- models/evm/gold/decoder/core_evm__ez_decoded_event_logs.sql
- models/evm/gold/decoder/core_evm__ez_decoded_event_logs.yml
- models/evm/silver/decoder/silver_evm__decoded_logs.sql
- models/evm/silver/tests/decoded_logs/test_silver_evm__decoded_logs_full.sql
- models/evm/silver/tests/decoded_logs/test_silver_evm__decoded_logs_full.yml
- models/evm/silver/tests/decoded_logs/test_silver_evm__decoded_logs_recent.sql
- models/evm/silver/tests/decoded_logs/test_silver_evm__decoded_logs_recent.yml
`dbt run -m models/evm/gold/decoder models/evm/gold/core/core_evm__dim_contracts.sql models/evm/silver/decoder models/evm/silver/tests/decoded_logs --full-refresh`
> An 5719/add decoding layer

- models/bronze/prices/bronze__complete_token_asset_metadata.sql
- models/bronze/prices/bronze__complete_token_prices.sql
- models/evm/gold/core/core_evm__ez_token_transfers.sql
`dbt run -m models/bronze/prices models/silver/prices models/gold/price models/evm/gold/core/core_evm__ez_token_transfers.sql --full-refresh`
> evm prices

- .github/workflows/dbt_run_scheduled_streamline_non_core.yml
- .github/workflows/dbt_run_streamline_external_points_balances_realtime.yml
- .github/workflows/dbt_run_streamline_external_realtime.yml
storefront has items again - re-enabling
> re-enable points requests
