- models/core/core__fact_blocks.sql
- models/core/core__fact_events.sql
- models/core/core__fact_nft_sales.sql
- models/core/core__fact_swaps.sql
- models/core/core__fact_transactions.sql
apr 20 is the earliest date we have where the `tx` object is not null
> expand core dates to 4/20

- models/core/core__dim_contract_labels.yml
- models/core/core__dim_topshot_metadata.sql
- models/core/core__dim_topshot_metadata.yml
- models/core/core__dim_validator_labels.yml
- models/core/core__fact_blocks.yml
- models/core/core__fact_bridge_transactions.yml
- models/core/core__fact_events.yml
- models/core/core__fact_nft_sales.yml
- models/core/core__fact_prices.yml
- models/core/core__fact_swaps.yml
- models/core/core__fact_transactions.yml
1. capitalizes the column name in the `yml` so snowflake runs `COMMENT`
2. explicitly lists column names for the topshot metadata (to drop `_inserted_timestamp`)
> AN-1822/caps for comment

- models/silver/silver__all_topshot_moments_minted_metadata_needed.sql
This adds TopShot `nft_ids` from nft sales to the metadata job, where previously we were only pulling new mints.
> AN-1830/topshot nft ids

- models/core/core__fact_prices.sql
- models/silver/silver__event_attributes.sql
- models/silver/silver__event_attributes_https.sql
- models/silver/silver__events_final.sql
Splits event handling before and after 7/18 to account for the move from gRPC to HTTPS.
On test failures:
- NFT issues documented in AN-1866 and will fix
- Bridge model issues documented in AN-1865 and will fix
- Sequence gaps should be filling with the latest Vertex update & I will get block heights to Paul for rewalking to get the event data from 7/18 to 8/5.
> AN-1837/events fix

- models/silver/silver__event_attributes_https.sql
Fixes missing event data 
Some known failures as ticketed [here](https://team-1612274056224.atlassian.net/browse/AN-1945?atlOrigin=eyJpIjoiNmYwOWY1MDMxZjI0NGI3M2I0NjkxYTJlMTY0NTAxZDIiLCJwIjoiaiJ9).
reminder - need to do a full refresh on _both_ event attribute models, everything downstream of them.
- for ad hoc run: `dbt run -s silver__event_attributes+ silver__event_attributes_https+ --full-refresh`
> AN-1988/events handle

- models/bronze/bronze__blocks.sql
- models/bronze/bronze__transactions.sql
- models/silver/silver__events.sql
New bloxy structure has the event contract and type in `qualifiedIdentifier` and `type` is now just the string "Events" and as we are backfilling a huge number of blocks, we are losing a lot of good data in the live models with the incremental strategy.
A refresh is going to take a _long_ time, so I suggest compiling the SQL and running the model in Snowflake, looking for where event contract is either an empty string `''` or where event type is `Event` (the current 2 issues this is solving)
> AN-2161/events location

- models/core/core__ez_bridge_transactions.sql
- models/core/core__ez_dex_swaps.sql
- models/core/core__ez_nft_sales.sql
- models/core/core__ez_staking_actions.sql
- models/core/core__ez_token_transfers.sql
- models/core/core__fact_blocks.sql
- models/core/core__fact_events.sql
- models/core/core__fact_transactions.sql
- models/core/core__fact_transactions.yml
- models/silver/silver__bad_events.sql
- models/silver/silver__bad_events.yml
- models/silver/silver__bridge_blocto.sql
- models/silver/silver__bridge_celer.sql
- models/silver/silver__event_attributes_https.sql
- models/silver/silver__events.sql
- models/silver/silver__events_final.sql
- models/silver/silver__nft_sales.yml
- models/silver/silver__nft_topshot_sales.sql
- models/silver/silver__nft_topshot_sales.yml
- models/silver/silver__nft_transactions_secondary_market.sql
- models/silver/silver__prices.sql
- models/silver/silver__staking_actions.sql
- models/silver/silver__swaps_events.sql
- models/silver/silver__token_transfers.sql
- models/silver/silver__transactions.yml
- models/silver/silver__transactions_blocto.yml
This closes the bug ticket by re-working the events model to take data from the decoded `payload` where it does not exist elsewhere in the data.
Known failures:
- there are 5 transactions that need to be re-walked as the `tx` object is null
- 235 missing blocks
- 60k missing transactions
I have a list of the blocks we need to re-walk to close out these errors and am ticketing for PL.
This PR also closes:
- AN-2166 by removing the data filter on core and releases the full chain to velocity
- AN-2169 checking the data by spork
> AN-2178/events fix

- tests/tests__moment_metadata_allday.sql
- tests/tests__moment_metadata_topshot.sql
Adds freshness tests for AllDay and TopShot metadata ingest, will fail if the data is > 1 day old.
Note - the lambda has not run in dev in a while so will fail. Test on prod:
`dbt test -s tests/tests__moment_metadata_allday.sql -t prod`
`dbt test -s tests/tests__moment_metadata_topshot.sql -t prod`
AllDay should alert, TopShot should pass.
> bespoke tests

- models/core/core__dim_topshot_metadata.yml
Issue is documented in AN-2263. Silencing the `not null` test as we are aware of the reason and will fix in due time.
> Silence Test

- tests/tests__block_timestamp_order.sql
Quickfix to add a custom test to ensure blocks are in order, as expected.
Run with:
`dbt test -s tests__block_timestamp_order`
> Block order test

- models/bronze/bronze__moments_metadata.sql
- models/streamline/streamline__all_topshot_moments_minted_metadata_needed.sql
- models/streamline/streamline__null_moments_metadata.sql
- New model to index every time (from 12/9 forward) we receive null metadata from a moment 
- Use model to ignore those ids when triggering streamline for metadata when it has been tried 3x
> An 2569/only retry req 3 times

- models/core/core__dim_moment_metadata.sql
- models/core/core__dim_moment_metadata.yml
- AllDay Historical 2 series has no metadata object, updated test
- 16 TXs minted a number of golazos NFTs without accompanying metadata, excluding those
> metadata update

- models/core/core__dim_topshot_metadata.yml
Moments of type `Fit Check` don't have a specific date, so adding where clause to the null test
> add exception to moment date test

- Makefile
- macros/utils.sql
- models/silver/streamline/core/history/streamline__get_blocks_history.sql
- Fixes json parse object for `get_blocks__history` sql
- Adds `undo clone` make file directive
- Adds `target database` grant privileges for `aws lambda` role macro
> Stream 97 blocks assembly

- Makefile
- models/silver/streamline/bronze/core/bronze__streamline_FR_blocks.sql
- models/silver/streamline/bronze/core/bronze__streamline_blocks.sql
- models/silver/streamline/core/complete/streamline__complete_get_blocks.sql
- models/silver/streamline/core/complete/streamline__complete_get_collections.sql
- models/silver/streamline/core/complete/streamline__complete_get_transaction_results.sql
- models/silver/streamline/core/complete/streamline__complete_get_transactions.sql
- models/silver/streamline/core/history/blocks/streamline__get_blocks_history_mainnet22.sql
- models/silver/streamline/core/history/collections/streamline__get_collections_history_mainnet22.sql
- models/silver/streamline/core/history/transaction_results/streamline__get_transaction_results_history_mainnet22.sql
- models/silver/streamline/core/history/transactions/streamline__get_transactions_history_mainnet22.sql
- Fixes `prod` `bronze` schema interpolation
- Removes hard coded `FLOW_DEV` schema from bronze models
- Adds logic to circumvent null incremental timestamp look up
- Tunes `blocks,coll,tx,tx_results` `udf params`
> fixed incremental complete runs

- Makefile
- models/silver/streamline/core/history/collections/streamline__get_collections_history_mainnet22.sql
- models/silver/streamline/core/history/transaction_results/streamline__get_transaction_results_history_mainnet22.sql
- models/silver/streamline/core/history/transactions/streamline__get_transactions_history_mainnet22.sql
There is an edge case where  due to the fact that we are excluding blocks from the blocks CTE if they have any collection in the `complete_get_collections` table, even if they don't have all the collections for that block.
This is the same for `transactions` & `transaction_results`, this PR implemets this logic for the `collections/tx/tx_results history` backfill models:
- From the `complete_get_blocks table`, we extract all `block_heights` and their associated `collection_ids`.
- We then identify which of these `collection_ids` are missing from the `complete_get_collections` table.
- Finally, we construct the `request` column for the missing `collection_ids`.
Similarly for `tx/tx_results` we use the following logic:
- From the complete_get_collections table, extract all transaction_ids. …
> bug fix for non block spine coll/tx ingestion

- .github/workflows/dbt_run_streamline_blocks.yml
- .github/workflows/dbt_run_streamline_collections.yml
- .github/workflows/dbt_run_streamline_transaction_results.yml
- .github/workflows/dbt_run_streamline_transactions.yml
Deleting the following from the GHA workflows due to the shared rate limit. This will leave all 4 methods for the RT models, and just blocks for mainnet 22.
```
- name: Run DBT History Jobs - Mainnet21
run: |
dbt run -s streamline__get_blocks_history --vars '{"STREAMLINE_INVOKE_STREAMS": True, "node_url": "access-001.mainnet21.nodes.onflow.org:9000", "start_block": 44950207, "end_block": 47169686}'
```
```
- name: Run DBT History Jobs - Mainnet22
run: |
dbt run -s 1+streamline__get_collections_history --vars '{"STREAMLINE_INVOKE_STREAMS": True, "node_url": "access-001.mainnet22.nodes.onflow.org:9000", "start_block": 47169687, "end_block": 55114466}'
- name: Run DBT History Jobs - Mainnet21
run: |
dbt run -s streamline__get_collections_history --vars '{"STREAMLINE_INVOKE_STREAMS": True, …
```
> Reduce backfill calls

- models/silver/streamline/core/realtime/streamline__get_collections_realtime.sql
- models/silver/streamline/core/realtime/streamline__get_transaction_results_realtime.sql
- models/silver/streamline/core/realtime/streamline__get_transactions_realtime.sql
Alter collections, transactions and transaction results realtime to properly filter the block range using the `last_3_days` CTE
> add last_3_days filter, rem tbl

- .github/workflows/dbt_run_moments_metadata.yml
- models/silver/_observability/silver_observability__block_tx_count.sql
- models/silver/nft/livequery/livequery__request_topshot_metadata.py
Updates usage of `udf_api` to the new deployment in `.live`
Note - there is an error with the dev deployment of `udf_get_chainhead()`, for testing change `{{ target.database }}` in `silver_observability__block_tx_count` to `flow` to use the prod deployment.
> AN-3890/migrate udf

- .github/workflows/dbt_observability_models.yml
- .github/workflows/dbt_test.yml
- models/descriptions/blocks_impacted_array.md
- models/descriptions/blocks_impacted_count.md
- models/descriptions/blocks_tested.md
- models/descriptions/max_block.md
- models/descriptions/max_block_timestamp.md
- models/descriptions/min_block.md
- models/descriptions/min_block_timestamp.md
- models/descriptions/test_name.md
- models/descriptions/test_timestamp.md
- models/silver/_observability/silver_observability__block_tx_count.sql
- models/silver/_observability/silver_observability__block_tx_count.yml
- models/silver/_observability/silver_observability__blocks_completeness.yml
- models/silver/_observability/silver_observability__txs_completeness.yml
- tests/tests__block_tx_count_recency.sql
Adds logic to query any gaps in the bitquery table. Gap may be due to unsealed blocks, so also adding a 500 block buffer on chainhead. We'd get them on the next run (happens 4x/day).
Currently getting no response for the 20 blocks from `60965021` to `60965040`
Adds recency tests to the complete blocks and txs table
> AN-3939/add fix gap logic and obs models tests

- models/silver/core/silver__streamline_transactions_final.sql
- models/silver/core/silver__streamline_transactions_final.yml
`GREATEST()` was resulting in null `_inserted_timestamp`s, adjusted logic per solution [here](https://stackoverflow.com/questions/74527418/how-to-use-greatest-in-snowflake-with-null-values)
> Quickfix - Update `retry_tx_ids` in txs final

- macros/custom_naming_macros.sql
- macros/dbt/get_tmp_relation_type.sql
- Change default merge behavior within Snowflake to use a temporary table instead of a temporary view. Temp tables are required for incremental predicates to work properly on merges.
> modify how dbt performs merges by default

- .github/workflows/dbt_test.yml
- models/descriptions/pending_result_response.md
- models/silver/core/silver__streamline_transactions_final.yml
- tests/tests__events_final_gap.sql
- tests/tests__streamline_blocks_gap.sql
- tests/tests__streamline_transaction_results_gap.sql
Adds tests to confirm txs final is properly building txs and not leaving anything behind
- pending_response is false earlier than current date (note - currently 1860 txs that were not ingested into silver__transaction_responses from S3. Will need to manually load these over)
- events final gap test 
Enables gap test in GHA config
> An 4050/txs final test

- .github/workflows/dbt_run_history.yml
4 streamline vars added as CLI input and set in the repository to allow for tweaking without PR. Currently set to the default value(s).
> add streamline vars as repo vars and upd history workflow

- models/descriptions/event_count.md
- models/gold/defi/defi__ez_swaps.sql
- models/gold/defi/defi__ez_swaps.yml
- models/silver/core/silver__streamline_events.sql
- models/silver/core/silver__streamline_events.yml
- models/silver/core/silver__streamline_transactions_final.sql
- models/silver/core/silver__streamline_transactions_final.yml
- models/silver/swaps/silver__swaps_events_s.sql
- models/silver/swaps/silver__swaps_s.sql
1. Adds a new col to txs final and events `events_count` (FR required on these 2). In every FLOW tx, the final 3 events are system events (token out, token in, fee paid). Count helps to ignore them in curated models
2. Filter out sys events from int model `silver__swaps_events_s`
3. Filter out xfers between `null` addresses. Transfers on FLOW often occur like: Withdraw 10 FLOW from Address 0x123. Withdraw 10 FLOW from `null` in subsequent events. This was leading to an over-filtering and causing swaps to be ignored. The `null` transfer can be ignored, focusing only on the transfer to/from an address.
> AN-4096/DEX Swaps Bug

- models/gold/beta/beta__ez_moment_player_ids.sql
- python/espn/README.md
- python/espn/get_espn.py
Adds beta view to map a player moment to their ESPN Player ID for ease of querying stats endpoint.
Note - uploading script used to query espn ID data as an archive / if we need to run it again to update.
> Beta allday espn id view

- tests/tests__block_tx_count_recency.sql
Legacy workflow that relied on the bitquery api for block tx counts
> disable block tx count recency test

- models/descriptions/amount_adj.md
- models/descriptions/deposited_uuid.md
- models/descriptions/deposited_uuid_root.md
- models/descriptions/from_address_balance_after.md
- models/descriptions/is_fee_transfer.md
- models/descriptions/to_address_balance_after.md
- models/descriptions/withdrawn_uuid_root.md
- models/gold/core/core__ez_token_transfers.sql
- models/gold/core/core__ez_token_transfers.yml
- models/silver/transfers/silver__token_transfers.sql
- models/silver/transfers/silver__token_transfers.yml
- models/silver/transfers/silver__token_transfers_s.sql
- models/silver/transfers/silver__token_transfers_s.yml
Deploys new transfers model for post-crescendo `Withdrawn` and `Deposited` events.
121 transfers in the old model, delete with:
```sql
delete from flow.silver.token_transfers_s
where block_height >= 85981726;
```
Migrates the `core.ez_token_transfers` from a view to incremental model with SO due to the `UNION ALL`
There's a number of new useful fields in the transfer events that Flow now emits. Most notably `balanceAfter` transfer could be easily mapped into a token balances table (for post-crescendo only).
> AN-5236/new transfers model

- models/evm/silver/core/silver_evm__traces.sql
- models/evm/streamline/realtime/streamline__get_evm_traces_realtime.sql
`dbt run -m models/evm/silver/core/silver_evm__traces.sql --full-refresh`
> An 5719/resume traces

- selectors.yml
- Reduces scope of `integration_tests` selector to only run `streamline udf api integration` tests
Example [error](https://github.com/FlipsideCrypto/flow-models/actions/runs/13000160880/job/36256975175#step:5:45)
Success running locally:
```
23:17:05  Concurrency: 12 threads (target='dev')
23:17:05  
23:17:05  1 of 1 START test test___utils_udf_introspect .................................. [RUN]
23:17:09  1 of 1 PASS test___utils_udf_introspect ........................................ [PASS in 3.76s]
23:17:09  
23:17:09  Running 2 on-run-end hooks
23:17:09  1 of 2 START hook: flow_models.on-run-end.0 .................................... [RUN]
23:17:09  1 of 2 OK hook: flow_models.on-run-end.0 ....................................... [OK in 0.00s]
23:17:09  2 of 2 START hook: …
```
> add _utils to integration_test selector

- .github/workflows/dbt_run_scheduled_reward_points_realtime.yml
- .github/workflows/dbt_run_streamline_evm_daily_silver.yml
- models/streamline/external/balances/streamline__reward_points_realtime.sql
- models/streamline/external/streamline__evm_addresses.sql
- models/streamline/external/transfers/silver_api__points_transfers.sql
- models/streamline/external/transfers/silver_api__points_transfers_response.sql
- models/streamline/external/transfers/streamline__points_transfers_realtime.sql
- tests/points/tests__unique_address_count_threshold.sql
1. Changes `points_transfers` workstream to use `transfers` as the exploded key and keeps `address` from the top-level json. Silver models adjusted accordingly
2. Balances gross batch size increased, using core instead of silver for `from_address`. Worker batch decreased to fan requests out over a greater period of time due to rate limit.
> flow rewards api fixes

- models/silver/core/silver__streamline_transaction_results.sql
- models/silver/core/silver__streamline_transactions_final.sql
- models/streamline/core/complete/streamline__complete_get_transaction_results.sql
- models/streamline/core/complete/streamline__complete_get_transactions.sql
- models/streamline/core/realtime/streamline__get_transaction_results_realtime.sql
- Deletes `DATA` from tx and txres complete models as it is not necessary for the realtime workflow. Can drop the col to save space.
- Adds a `MANUAL_FIX` clause to silver transaction results to rerun the gap range(s)
- Adds a `RETRY_WINDOW` var to transactions final as the initial error was >7d ago.
Example (can modify range to the gap over 3/28-29).
`dbt run -s silver__streamline_transaction_results --vars '{"MANUAL_FIX": True, "RANGE_START":108800000, "RANGE_END": 108800000}'`
- [Run result](https://app.snowflake.com/zsniary/exa10207/#/compute/history/queries/01bb89f0-0414-a5b1-3d4f-83031ebbe03b/detail) of this range, which otherwise raises an overflow error.  
And then `dbt run -s silver__streamline_transactions_final --vars '{"RETRY_WINDOW": 14}'`
Note: the external table …
> Modify Transaction Results

- .github/workflows/dbt_run_streamline_blocks.yml
- .github/workflows/dbt_run_streamline_collections.yml
- .github/workflows/dbt_run_streamline_transaction_results.yml
- .github/workflows/dbt_run_streamline_transactions.yml
- models/streamline/core/realtime/streamline__get_transaction_results_realtime.sql
Sets a starting block height to backfill missing txs starting in late March.
Run with `dbt run -s streamline__get_transaction_results_realtime --vars '{"STREAMLINE_BACKFILL": True, "STREAMLINE_INVOKE_STREAMS": True, "sql_limit": 700000}'`
> set lookback block height

- models/gold/defi/defi__ez_bridge_activity.yml
- models/gold/defi/defi__fact_bridge_activity.yml
Stargate bridge is on EVM so `block_height ` filter for recency doesn't correctly apply to those tx's
> remove block filter on bridge recency

- .github/workflows/dbt_run_scheduled_streamline_non_core.yml
- .github/workflows/dbt_run_streamline_external_realtime.yml
Removes just the call to the `transaction_entries` API endpoint, but allows for the storefront call
Triaging and fixing snag api call with ticket AN-6534
> rm tx entries from gha

- models/gold/rewards/rewards__fact_points_transfers.sql
- models/gold/rewards/rewards__fact_points_transfers.yml
- models/gold/rewards/rewards__fact_transaction_entries.sql
Current data flows into `fact_transaction_entries` through the Snag API, but old data remains in `fact_points_transfers`. This PR will union the `transaction_entries` model into the points_transfers while retaining information.
Result from Claude Code
> AN-6549 Merge Points
